var GAME_LEVELS = [
  ["xxxxxxxx!!!!!!!!!!!!!!!!!!!!!xxxxxxxxxxxxxxxx!!x!!x!!x!!x!!x!!x!!!!!=       x!! ",
   " !!!!!!!!!xxxxxxxxxxxxxxxxxxxx=    y      xxxxxxxxxxxxxxxxxxxxxxxxxxv        xv ",
   " vxxxxxxxx     Y     Y             y          y   y      y       y y            ",
   "    Y   Y      Y     Y                            y      y       y              ",
   "        Y            Y    c                              y       y              ",
   "        Y                                                                       ",
   "                         xxxx       y                y             xxx      yyy ",
   "                           yxxx                    xx      xx    xx!xx          ",
   "         y        xxxx               o o      xx            y    x!!!x          ",
   "  o  yyyyyy          y                         y             y   xx!xx       o  ",
   "         y                 y         xxxxx                         xvx          ",
   " !xxy          xxx                     y                y                     x ",
   " !!xxxxxxx      y                            o                              x   ",
   " xvx y                            xxx                     xx             y   x  ",
   " x x               y             y       y    xxxxx          y    xx        xx  ",
   " x x         xxxx          o  yyy      xxx!!!!!xxx                      xxxx    ",
   " x x  @     xxy!x  p                 xxx!!!!v!!!!!xxxx                 xy       ",
   " x xxxxxxxxxy!!!!xxxxxx  xxxxxxxx   xx!!!!!!v v!!!!!!!xxx    xxxxxxxxxxy        ",
   " x xy     xxy!!!!!x!!xx  xx     x   xyyyyyyyyyyyyyyyyyyxx    xy        y        ",
   " xyx y        xxx!!!!vx!!x    y  x!!!xyyyyyyyyyyyyyyyyyyxx!!!!xy    y           ",
   " x!!      y            xxxx       x!!!x!!!!!!yyyyy!!!!!!!x!!!!!x                ",
   " x!              y              xxxxx!!!!!!!!!!!!!!!!!!xxxxxxx           y      ",
   "  !!!                                                                           ",
   "  !!                            y                                               "],
  ["                                      x!!x                        xxxxxxx                                    x!x  ",
   "                                      x!!x                     xxxx     xxxx                                 x!x  ",
   "                                      x!!xxxxxxxxxx           xx           xx=                               x!x  ",
   "                                      xx!!!!!!!!!!xx         xx             xxxxxxxxxxxxxxxx                 x!x  ",
   "                                       xxxxxxxxxx!!x         x                                    o       o  x!x  ",
   "                                                xx!x         x         o                                    xx!x  ",
   "                                                 x!x         x    x                           xxxxxxxxxxxxxxx!!x  ",
   "                                                 xvx         x     x   x                        p!!!!!!!!!!!!!xx  ",
   "                                                             xx  |   |   |                x xxxxvxxxxxxxxxxxxxx   ",
   "                                                              xx!!!!!!!!!!x                                       ",
   "     0                                                         xxxx!!!!!xxxx                                      ",
   "                 y    y                     x           m x            xxxxxxx                    xxx             ",
   "                   y                        x            x                                        xvx             ",
   "                                            x           x      y   y              x              x                ",
   "     xxx      y  o          y               x          x       y                   xx            x                ",
   "!!    y    yy              y   y            xx         x                             x           x                ",
   "!x                                           xx       x      o  o    x   x            x         xxxx              ",
   "v              xxxxxxx        xxx   xxx      x        x              x   x   p       x        xxx                 ",
   "              xx     xx         x   x        x       xx     xxxxxx   x   x   xxxxxxxxx       x                    ",
   "           xxxxy     yxxxx      x o x        x        xx             x   x   x                x                   ",
   "     @      yx         xx       x   x        x         x             x   x   x                x                   ",
   "    xxx      x    y     x       x   x          x      xxxx           x   xxxxx   xxxxxx       x                   ",
   "    x x      x    y     x      xx o xx         x     x=              x     o     x!xyyy        x                  ",
   "!!!!x x!!!!!!x          x!!!!!!xx     xx!!!!!!!!xx    x!!!!!!!!!!  c  x     =     x!x         x                   ",
   "!!!!x x!!!!!!x          x!!!!!xx       xxxxxxxxxx     x!!!!!!!xx!  p  xxxxxxxxxxxxx xx  o o xxx                   ",
   "!!!!x x!!!!!!x          x!!!!!x   o                  xx!!!!!!xx !         y          xx     xx                    ",
   "!!!!x x!!!!!!x          x!!!!!x                     xx!!!!!!xx  !                     xxxxxxx                     ",
   "!!!!x x!!!!!!x          x!!!!!xx       xxxxxxxxxxxxxx!!!!!!xx   !                      y                          ",
   "!!!!x x!!!!!!x          x!!!!!!xxxxxxxxx!!!!!!!!!!!!!!!!!!xx    !           y                                     ",
   "!!!!x x!!!!!!x          x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xx     !                                                 "],
  ["                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                        o                                                                     ",
   "                                                                                                              ",
   "                                        x                                                                     ",
   "                                        x                                                                     ",
   "                                        x                                                                     ",
   "                                        x                                                                     ",
   "                                       xxx                                                                    ",
   "                                       x x                 !!!        !!!  xxx                                ",
   "                                       x x                 !x!        !x!                                     ",
   "                                     xxx xxx                x          x                                      ",
   "                                      x   x                 x   oooo   x       xxx                            ",
   "                                      x   x   c             x          x      x!!!x                           ",
   "                                      x   x                 xxxxxxxxxxxx       xxx                            ",
   "                                     xx   xx      x   x      x                                                ",
   "                                      x   xxxxxxxxx   xxxxxxxx              x x                               ",
   "                                      x   x           x                    x!!!x                              ",
   "                                      x   x           x                     xxx                               ",
   "                                     xx   xx          x                                                       ",
   "                                      x   x= = = =    x            xxx                                        ",
   "                                      x   x           x           x!!!x                                       ",
   "                                      x   x    = = = =x     o      xxx       xxx                              ",
   "                                     xx   xx          x                     x!!!x                             ",
   "                              o   o   x   x           x     x                xxv        xxx                   ",
   "                                      x   x           x              x                 x!!!x                  ",
   "                             xxx xxx xxx xxx     o o  x!!!!!!!!!!!!!!x                   vx                   ",
   "                             x xxx x x xxx x          x!!!!!!!!!!!!!!x                                        ",
   "                             x             x   xxxxxxxxxxxxxxxxxxxxxxx                                        ",
   "                             xx           xx                                         xxx                      ",
   "  xxx                         x     x     x                                         x!!!x                xxx  ",
   "  x x                         x    xxx    x                                          xxx                 x x  ",
   "  x                           x    xxx    xxxxxxx           y           xxxxx                             x  ",
   "  x                           x           x                              x   x                             x  ",
   "  x                    y      xx          x                              x x x                             x  ",
   "  x                                       x       |xxxx|    |xxxx|     xxx xxx                             x  ",
   "  x                xxx             o o    x                              x         xxx                     x  ",
   "  x               xxxxx       xx          x                             xxx       x!!!x          x         x  ",
   "  x               oxxxo       x    xxx    x                             x x        xxx          xxx        x  ",
   "  x                xxx        xxxxxxxxxxxxx  x oo x    x oo x    x oo  xx xx                    xxx        x  ",
   "  x      @   x      x         x           x!!x    x!!!!x    x!!!!x    xx   xx                    x         x  ",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxx           xxxxxxxxxxxxxxxxxxxxxxxxxxxxx     xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  ",
   "                                                                                                              ",
   "                                                                                                              "],
  ["                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "         y    y      yyy     y    y             y       y    yyy     yy    y    !                             ",
   "          y  y      y   y    y    y             y       y   y    y   y y   y    !                             ",
   "           y       y     y   y    y             y   y   y  y      y  y  y  y    !                             ",
   "           y        y   y    y    y             y  y y  y   y    y   y   y y    v                             ",
   "           y         yyy      yyyy y              y   y      yyyy    y    yy                                  ",
   "                                                                                                              ",
   "                                                                                                              ",
   "  x  @                                          o                                                             ",
   "  xxxxxxx                                     xxxxx       xx     xx     xxx                                   ",
   "        x=        p         =       p        =x   x                     xxx                                   ",
   "        xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx   x!!!!!!!!!!!!!!!!!!!!!xxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "                                                  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "                                                                                                              "]
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
